---
- hosts: localhost
  remote_user: ubuntu
  user: ubuntu
  tasks:
    - name: Add ppa Repository
      sudo: yes
      apt_repository: repo=ppa:ondrej/{{ php.ppa }}

    - name: General | Install required packages.
      apt: name={{ item }} state=latest update_cache=yes
      tags: common
      sudo: yes
      with_items:
        - php7.0
        - php7.0-bcmath
        - php7.0-bz2
        - php7.0-curl
        - php7.0-dba
        - php7.0-dom
        - php7.0-gd
        - php7.0-fpm
        - php7.0-json
        - php7.0-mcrypt
        - php7.0-mongo
        - php7.0-soap
        - php7.0-readline
        - php7.0-zip
        - php7.0-xml
        - git
        - ruby
        - build-essential
        - libssl-dev

    - name: Composer | Install PHP Composer
      action: shell curl -sS https://getcomposer.org/installer | php && mv composer.phar /usr/local/bin/composer

    - name: Install nvm
      shell: >
        curl https://raw.githubusercontent.com/creationix/nvm/v0.17.0/install.sh | bash
        creates=/home/{{ ansible_user_id }}/.nvm/nvm.sh

    - script:
        name: update node
        code: |-
          curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -
          sudo apt-get install -y nodejs

    - name: Install NPM build tools
      npm: name={{ item }} global=yes
      with_items:
        - bower
        - gulp-imagemin
        - gulp

    - name: Install bundler
      gem: name=bundler


