---
- hosts: localhost
  remote_user: ubuntu
  user: ubuntu
  tasks:
    - name: General | Install required packages.
      apt: name={{ item }} state=latest update_cache=yes
      tags: common
      sudo: yes
      with_items:
        - php5-mcrypt
        - php5-fpm
        - php5-cli
        - php5-curl
        - git
        - ruby
        - build-essential
        - libssl-dev
        #- redis

    - name: Enable php5-extensions
      action: shell sudo php5enmod {{ item }}
      with_items:
        - mcrypt
        - curl

    - name: Composer | Install PHP Composer
      action: shell curl -sS https://getcomposer.org/installer | php && mv composer.phar /usr/local/bin/composer

    - name: Install node and set version
      shell: >
        curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash - && sudo apt-get install -y nodejs
      register: nodeinstall

    - name: Update npm to version 2
      shell: sudo npm install -g npm@latest-2

    - name: Node install debug
      debug: var=nodeinstall

    - name: Debugging
      shell: whoami
      register: whoami

    - name: debug
      debug: var=whoami

    - name: Install NPM build tools
      npm: name={{ item }} global=yes
      with_items:
        - bower
        - gulp-imagemin
        - gulp

    - name: Install bundler
      gem: name=bundler

    - name: Create dosomething user
      user: name=dosomething shell=/bin/bash generate_ssh_key=yes password={{ createpassword }}
      sudo: true
      tags: user

    - name: Sudoers | update sudoers file and validate
      lineinfile: "dest=/etc/sudoers
        insertafter=EOF
        line='dosomething ALL=(ALL) NOPASSWD: ALL'
        regexp='dosomething ALL=(ALL) NOPASSWD: ALL'
        state=present"
      sudo: true
      tags: user

