---
- hosts: localhost
  remote_user: ubuntu
  user: ubuntu
  tasks:
    - name: update node
      shell: -curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -

    - name: Add ppa Repository
      sudo: yes
      apt_repository: repo=ppa:ondrej/php

    - name: General | Install required packages.
      apt: name={{ item }} state=latest update_cache=yes
      tags: common
      sudo: yes
      with_items:
        - php7.0
        - php7.0-bcmath
        - php7.0-bz2
        - php7.0-curl
        - php7.0-dba
        - php7.0-dom
        - php7.0-gd
        - php7.0-fpm
        - php7.0-json
        - php7.0-mcrypt
        - php7.0-soap
        - php7.0-readline
        - php7.0-zip
        - php7.0-xml
        - nodejs
        - git
        - ruby
        - build-essential
        - libssl-dev

    - name: Pecl install mongo
      shell: pecl install mongodb

    - name: Composer | Install PHP Composer
      action: shell curl -sS https://getcomposer.org/installer | php && mv composer.phar /usr/local/bin/composer

    - name: Install NPM build tools
      npm: name={{ item }} global=yes
      with_items:
        - bower
        - gulp-imagemin
        - gulp

    - name: Install bundler
      gem: name=bundler


